# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# language ja

# package org.apache.catalina.realm

jaasRealm.accountExpired=ユーザ名 [{0}] はアカウントの期限が切れているために認証されません
jaasRealm.authenticateSuccess=ユーザ名 [{0}] は認証に成功しました
jaasRealm.credentialExpired=ユーザ名 [{0}] は証明書の期限が切れたために認証されません
jaasRealm.failedLogin=ユーザ名 [{0}] はログインに失敗したために認証されませんでした
jaasRealm.loginException=ユーザ名 [{0}] の認証中にログイン例外が発生しました
jaasRealm.unexpectedError=予測しないエラーです
jdbcRealm.authenticateFailure=ユーザ名 [{0}] は認証に失敗しました
jdbcRealm.authenticateSuccess=ユーザ名 [{0}] は認証に成功しました
jdbcRealm.close=データベース接続クローズ中の例外です
jdbcRealm.exception=認証実行中の例外です
jdbcRealm.open=データベース接続オープン中に例外が発生しました
jndiRealm.authenticateFailure=ユーザ名 [{0}] は認証に失敗しました
jndiRealm.authenticateSuccess=ユーザ名 [{0}] は認証に成功しました
jndiRealm.close=ディレクトリサーバ接続クローズ中の例外です
jndiRealm.exception=認証実行中の例外です
jndiRealm.open=ディレクトリサーバ接続オープン中の例外です
memoryRealm.authenticateFailure=ユーザ名 [{0}] は認証に失敗しました
memoryRealm.authenticateSuccess=ユーザ名 [{0}] は認証に成功しました
memoryRealm.loadExist=メモリデータベースファイル [{0}] を読むことができません
memoryRealm.loadPath=メモリデータベースファイル [{0}] からユーザをロードします
memoryRealm.readXml=メモリデータベースファイルを読み込み中の例外です
realmBase.algorithm=無効なメッセージダイジェストアルゴリズム [{0}] が指定されています
realmBase.digest=ユーザの証明書のダイジェストエラー
realmBase.forbidden=要求されたリソースへのアクセスが拒否されました
realmBase.hasRoleFailure=ユーザ名 [{0}] はロール [{1}] を持っていません
realmBase.hasRoleSuccess=ユーザ名 [{0}] はロール [{1}] を持っています
realmBase.authenticateFailure=ユーザ名 [{0}] は認証に失敗しました
realmBase.authenticateSuccess=ユーザ名 [{0}] は認証に成功しました
userDatabaseRealm.lookup=キー [{0}] でユーザデータベースを検索中の例外です
userDatabaseRealm.noDatabase=キー [{0}] でユーザデータベースコンポーネントが見つかりません
dataSourceRealm.authenticateFailure=ユーザ名 [{0}] は認証に失敗しました
dataSourceRealm.authenticateSuccess=ユーザ名 [{0}] は認証に成功しました
dataSourceRealm.close=データベース接続をクローズ中の例外です
dataSourceRealm.exception=認証を実行中の例外です

